In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
#creating the 0 dimendion array
arrzeros=np.array(87)
print(np.ndim(arrzeros))


0


In [4]:
arr2=np.array([[3,4],[6,7]])
arr2.ndim

2

In [5]:
np.size(arr2)

4

In [6]:
#check memory
arr2.nbytes
arr2.dtype

dtype('int64')

In [7]:
arr1=np.array([[1,2,3,4],
               [5,6,7,8]])

s=arr1[0,-2]
print(s)

3


In [8]:
arr1[0,:]

array([1, 2, 3, 4])

In [9]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr3[:5]

array([1, 2, 3, 4, 5])

In [11]:
#zero matrix
np.zeros((6,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
np.full((40,40),560)

array([[560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       ...,
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560]])

In [14]:
from numpy import random 

In [15]:
random.randint(100)

31

In [16]:
np.random.rand(7,4) #to get random values in matrix

array([[0.16315477, 0.38685582, 0.19351928, 0.19850964],
       [0.66723311, 0.62260524, 0.87340799, 0.06852102],
       [0.21102674, 0.75186726, 0.94166346, 0.79393954],
       [0.19593786, 0.89115913, 0.830322  , 0.091593  ],
       [0.90965383, 0.19888544, 0.21250704, 0.98080957],
       [0.49629946, 0.18299724, 0.80471943, 0.22327314],
       [0.75793627, 0.44267279, 0.01337714, 0.81933279]])