In [1]:
#mathemtics,engg,scientific data
# numpy:python+c (python is embedded and extended)


#### #how to create basic array

In [2]:
 
import numpy as np

In [3]:
np.zeros(4) #can only be used for 1 d array
np.ones(3)

array([1., 1., 1.])

In [4]:
np.empty(4)


array([0., 0., 0., 0.])

In [5]:
np.arange(4) #elements in certain range

array([0, 1, 2, 3])

In [6]:
np.arange(2,9,3) #specify first number ,last number and space

array([2, 5, 8])

In [7]:
np.linspace(0,10,5)#array with values that are spaced linearly in a specified imterval
# np.linspace(start,end,no.of element required)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
x=np.ones(4,dtype=np.int64)  #to specify the data type
x

array([1, 1, 1, 1])

### Adding, Removing and Sorting element

In [9]:
arr=np.array([[7,6,8,5],[9,3,4,6]])
print(arr)  # to sort the given array
np.sort(arr)

[[7 6 8 5]
 [9 3 4 6]]


array([[5, 6, 7, 8],
       [3, 4, 6, 9]])

In [10]:
a=np.array([1,2,3,4])
b=np.array([8,6,9,4])
c=np.array([11,12,14,15])

np.concatenate((a,b,c),axis=0) #2D array require 2 brackets

array([ 1,  2,  3,  4,  8,  6,  9,  4, 11, 12, 14, 15])

In [11]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### How do you know the shape and size of an array?

In [12]:
#using ndim,shape,size

#### How to convert a 1-D array into 2-D array(how to add new axis to an array)

In [13]:
a=np.array([1,2,3,4,5])
np.shape(a)

(5,)

In [14]:
a2=a[np.newaxis,:] #add a new row
a2.shape
#print(a2)

(1, 5)

In [15]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [16]:
b=np.expand_dims(a,axis=0)
b.shape

(1, 6)

In [17]:
c=np.expand_dims(a,axis=1)
c.shape

(6, 1)

### Indexing and Slicing

In [18]:
data=np.array([1,2,3])
data[2]

data[0:2]
data[1:2]
data[-1:]

array([3])

In [19]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,18]])
a.shape

print(a[a<7])

[1 2 3 4 5 6]


In [20]:
five_up=(a>=5)   #a[...]=print numerical element
print(a[five_up]) # [...]=print boolean

[ 5  6  7  8  9 10 11 18]


In [21]:
divisible_by_2= (a[a%2==0])
print(divisible_by_2)

[ 2  4  6  8 10 18]


In [22]:
c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [23]:
five_up=(a>5)| (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [24]:
## ZIP? np.nonzero?

### How to create an array from existing data


In [25]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=a[0:10:2]
arr1

array([1, 3, 5, 7, 9])

In [26]:
a1=np.array([[1,2],[3,4]]) #vstack= vertically
a2=np.array([[3,3],[4,4]]) #hstack=horizontally
np.hstack((a1,a2))

array([[1, 2, 3, 3],
       [3, 4, 4, 4]])

In [27]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [28]:
b=a[0,:]
#print(b)
b[0]=99
print(b)
print(a)


[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Basic array operations

In [29]:
data=np.array([1,2])
ones=np.ones(2,dtype=int)
print(data+ones)
print(data-ones)
print(data*data)
print(data/data)
print(data/ones)


[2 3]
[0 1]
[1 4]
[1. 1.]
[1. 2.]


In [30]:
a=np.array([1,2,3,4])
np.sum(a) # a.sum()

10

In [31]:
#operation btw scalar and vector
#broadcasting allows numpy to perform operation on array of different shape



In [32]:
data=np.array([1,2])
data*1.6

array([1.6, 3.2])

In [33]:
z=np.array([2,4,7,5,9,8,])
print(z.max())  #maximum element of array
print(z.min())
print(z.sum())

9
2
35
